# Generated by Django 4.1.2 on 2022-10-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_podcasts',
            field=models.ManyToManyField(to='core.podcast'),
        ),
    ]
